source 'https://rubygems.org'
gem 'cleverbot_io'
gem 'discordrb', git: 'https://github.com/meew0/discordrb.git',
                 branch: 'master'
gem 'dotenv'
gem 'json'
gem 'rufus-scheduler'
gem 'sys-uptime'
gem 'time_difference'
gem 'titleize', '~> 1.4'
