source 'https://rubygems.org'
gem 'cleverbot-api'
gem 'discordrb', git: 'https://github.com/Reaver01/discordrb',
                 branch: 'enhance/default_channel'
gem 'dotenv'
gem 'json'
gem 'rufus-scheduler'
gem 'sys-uptime'
gem 'time_difference'
gem 'titleize', '~> 1.4'
